### ISSUE TITLE
Ability to show tooltip without over event

### ISSUE THREAD

**Issue by danielok1303** [PygmySlowLoris/vue-fab#10]
I would like when opening the actions all tooltips are displayed without mouse over event, this feature is essential for mobile viewing

**Comment by Edujugon** [comment]
Hi @danielok1303 

I'll try to add that feature into the next release :)

**Comment by Edujugon** [comment]
Hi @danielok1303 ,

I've just released a new package version (v2.1.0) which covers your request :)

Have a look at that and let me know how that works for you.

Enjoy

**Comment by Edujugon** [comment]
Hi @danielok1303 ,
Could you try the last release with the feature you requested? Did that work for you?

**Comment by danielok1303** [comment]
Hi @Edujugon, 
sorry for the delay in answering. It worked perfectly for me, thank's very much

**Comment by Edujugon** [comment]
You're welcome!

Glad to know it worked for you :)
