### ISSUE TITLE
Doble Click on Fab buttons

### ISSUE THREAD

**Issue by jgnovais** [PygmySlowLoris/vue-fab#11]
hi.
 i'm using fab  with the tooltip on fabButtons, like issue #10 .

But when i do duble click on Fab, The fabButtons missing but his tooltips not.

**Comment by hazzo** [comment]
Hi @jgnovais, how are you triggering the fab action buttons with double click? Some code sample will be good for helping.

**Comment by jgnovais** [comment]
Yes it is with a double click.
Tomorrow morning i will send a print screen.

**Comment by jgnovais** [comment]
![image](https://user-images.githubusercontent.com/20583323/30742778-13506844-9f71-11e7-9658-3052829f1044.png)

**Comment by hazzo** [comment]
Yes I understand what you mean, but how are you implementing double click with our fab? We don't support from the box any other event than simple click...

**Comment by jgnovais** [comment]
Just click twice on fab, i implemented nothing :D

**Comment by hazzo** [comment]
Well that's why it's happening. Consecutive double click has apparently a bug where the tooltips don't have enough time to appear and lose their anchors. If you click once let the buttons appear and then click again this won't happen. I'll investigate deeper about this bug.

**Comment by jgnovais** [comment]
Thanks

**Comment by hazzo** [comment]
Hi @jgnovais,

issue has been fixed on ralease 2.1.1.
Update, try it and please don't doubt on commenting here again.

Thanks for reporting.

**Comment by jgnovais** [comment]
\o/ Thanks i will to do this

**Comment by jgnovais** [comment]
Thanks @hazzo very well :+1:
