### ISSUE TITLE
No fab actions

### ISSUE THREAD

**Issue by blurdylan** [PygmySlowLoris/vue-fab#17]
I need to be able to click on the main button and fire events without opening the smaller buttons.

**Comment by blurdylan** [comment]
Instead, when I use `@click` or `@click.native` on the main button, an error is logged

```js
[Vue warn]: Error in callback for watcher "toggle": "TypeError: Cannot read property 'length' of undefined"
found in
---> <Fab> at node_modules\vue-fab\src\FAB.vue
```

**Comment by Edujugon** [comment]
Hi @blurdylan ,

We've just released a new package version with that fix.
Now you can use `@click.native` on the main button.

**Comment by jvb93** [comment]
@Edujugon ugh the FAB rotates and doesn't un-rotate with this method? any tips?

**Comment by Edujugon** [comment]
Hi @jvb93 ,

I'm trying to reproduce the issue but it actually rotates and un-rotates just fine.
Could you share some code snippet to see how you're using the component?

**Comment by Edujugon** [comment]
Hey, I think I was not getting your point...But now I guess I do.

So basically when you click on the button it rotates and keeps that position.

What would be the desired behaviour?
* no rotate at all and trigger that event
* rotate, trigger the event and rotate back

**Comment by jvb93** [comment]
@Edujugon Hmm yeah this is interesting. If there is no menu to display, then the animation to rotate doesn't make much sense at all, as it's not, say rotating to open. Here's what I propose:

- Provide a prop that would allow the developer to choose whether or not to rotate
- OR if there are no actions, do not rotate at all.

EIther way, I am down to code this and PR, no worries.
