### ISSUE TITLE
Custom colors for each menu

### ISSUE THREAD

**Issue by mifas** [PygmySlowLoris/vue-fab#2]
Is possible to customize each menu with colour? Possible to `color `property for `fabActions`

**Comment by hazzo** [comment]
Hi mifas,

do you mean a specific color for each action button in the FAB? Or for the whole list? 
I had the idea of using the main color and tint the action buttons lighter or darker based in a prop. But not changing the color completely of the actions inside the FAB menu.

Thanks for contributing!

**Comment by mifas** [comment]
Yes, specific color for each Fab action. Like below 
![screenshot-pygmyslowloris github io-2017-05-22-20-05-35](https://cloud.githubusercontent.com/assets/4384874/26314000/2f7e3566-3f2a-11e7-8ceb-75e5dc643b76.png)

**Comment by Edujugon** [comment]
@mifas 
We've already added the requested feature to the latest version.

Just need to add a new prop `color` to your action object.
Anyway, You can have a look at [documentation](https://github.com/PygmySlowLoris/vue-fab/#actions) to get more details.

**Comment by mifas** [comment]
Thanks for the update. It's working
