### ISSUE TITLE
fab with event

### ISSUE THREAD

**Issue by TankeRubio** [PygmySlowLoris/vue-fab#24]
could it be possible we have a fab with only one event? i mean when you click the fab an event begins. not to show more buttons. Please :)

**Comment by jvb93** [comment]
@TankeRubio see #17

**Comment by Edujugon** [comment]
Hi @TankeRubio ,

As @jvb93 pointed correctly you can take a look at #17 issue.

Simply use `@click.native` on the component and it will trigger that event when clicking on the main button.
