### ISSUE TITLE
Make Fab Open by default

### ISSUE THREAD

**Issue by legreco** [PygmySlowLoris/vue-fab#28]
How to make the fab-component to be open by default?

**Comment by Edujugon** [comment]
Hi @legreco ,

We've just released a new version allowing via prop to start with the fab opened.

the prop is : `start-opened`

Have a look at the [documentation](https://github.com/PygmySlowLoris/vue-fab#properties) for more details.

Hope this helps

**Comment by legreco** [comment]
I just installed the new version and with the prop "start-opened" set to true, the fab is opened by default. Thanks for the help.
I will close and open another issue related to this new functionnality.
https://github.com/PygmySlowLoris/vue-fab/issues/30
