### ISSUE TITLE
Possible to resize icon size

### ISSUE THREAD

**Issue by mifas** [PygmySlowLoris/vue-fab#3]
Hi

Is possible to resize the main icons and sub action's icons? Currently is quite big

**Comment by Edujugon** [comment]
Hi @mifas ,

Yeah, we'll add that feature in the coming version.

I'm updating this thread as soon as it's done.

**Comment by hazzo** [comment]
Hi @mifas,

Since version 2.0.9 now the fab can be adjusted in three sizes: 'small', 'medium' and 'large' be using the prop 'icon-size'.

I used the material icon size example to resize the fab.

```
/* Rules for sizing the icon. */
.material-icons.md-18 { font-size: 18px; }
.material-icons.md-24 { font-size: 24px; }
.material-icons.md-36 { font-size: 36px; }
.material-icons.md-48 { font-size: 48px; }
```
If this sizes don't suit your necessities you can override the fab giving it a custom class.
